server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/myrealm
#          jwk-set-uri: http://localhost:8080/realms/myrealm/protocol/openid-connect/certs

keycloak:
  auth-server-url: http://localhost:8082
  realm: myrealm
  client-id: keycloak-client
  client-secret: 6YjJbZuZbdPKbzVs15XHfKycOrLTs33E
  username-admin-client: admin
  password-admin-client: admin

uri:
  token: http://localhost:8082/realms/myrealm/protocol/openid-connect/token
  person-service:
    baseURL: http://localhost:8083
    individuals: /api/v1/individuals

jwt:
  header: Authorization


